# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
